#!/bin/bash

echo "*  *  *  *  *"
echo "Current running process"
echo "*  *  *  *  *"

docker-compose top

docker-compose down 

if [[ $(docker-compose top) ]]; then
	docker-compose top
else
	echo "*  *  *  *  *  *  *  *  *"
	echo "Processes have been deleted"
	echo "*  *  *  *  *  *  *  *  *"
fi

# echo if there is no output that is was successful
