#!/bin/bash

user=dimitrioskay

# log into your DockerHub
## docker login -u=$user

# OPTIONAL? push image to personal docker hub repo

sudo dockerd

# run docker-compose commands
sudo docker-compose up -d
